# MQTT Configuration
[MQTT]
broker = mqtt.example.com
port = 1883
topic = sensor/data
client_id = device_hostname
# If no authentication is used, leave these blank, otherwise provide the proper values and an authenticated connection will be used
username = 
password = 
tls_enabled = true    # Enable TLS
skip_verify = true    # Skip certificate verification (useful for self-signed certificates)

# Application Settings
[App]
log_level = info
interval = 5  # Seconds between data transmissions
